version: 2.1

commands:
  checkout_with_workspace:
    steps:
      - checkout
      - attach_workspace:
          at: ~/

jobs:
  build:
    docker:
      - image: cimg/php:7.4-browsers
    steps:
      - checkout_with_workspace
      - run:
          name: Install dependencies
          command: npm ci
      - persist_to_workspace:
          root: ~/
          paths:
            - project

  lint:
    docker:
      - image: cimg/php:7.4-browsers
    steps:
      - checkout_with_workspace
      - run:
          name: Run JS linter
          command: npm run lint

  test-js:
    docker:
      - image: cimg/php:7.4-browsers
    steps:
      - checkout_with_workspace
      - run:
          name: Run JS Tests
          command: npm run test

  php-lint:
    docker:
      - image: cimg/php:7.4
    steps:
      - checkout_with_workspace
      - run:
          name: Composer install
          command: composer install
      - run:
          name: PHP lint
          command: composer lint

  release:
    docker:
      - image: cimg/php:7.4-browsers
    steps:
      - checkout_with_workspace
      - run:
          name: Install rsync
          command: sudo apt-get update && sudo apt-get install rsync
      - run:
          name: Release new version
          command: npm run release

  post_release:
    docker:
      - image: cimg/php:7.4-browsers
    steps:
      - checkout_with_workspace
      - run:
          name: Perform post-release chores
          command: ./node_modules/newspack-scripts/post-release.sh

workflows:
  version: 2
  all:
    jobs:
      - build
      - lint:
          requires:
            - build
      - test-js:
          requires:
            - build
      - php-lint:
          requires:
            - build
      - release:
          requires:
            - build
          filters:
            branches:
              only:
                - release
                - alpha
                - /^hotfix\/.*/
      - post_release:
          requires:
            - release
          filters:
            branches:
              only:
                - release
